import { GoogleGenAI, Chat } from "@google/genai";

let chatSession: Chat | null = null;
let aiInstance: GoogleGenAI | null = null;

const getAIInstance = () => {
  if (!aiInstance) {
    if (!process.env.API_KEY) {
      console.error("API Key missing");
      throw new Error("API Anahtarı bulunamadı.");
    }
    aiInstance = new GoogleGenAI({ apiKey: process.env.API_KEY });
  }
  return aiInstance;
};

export const initializeChat = async (dataContext: string) => {
  const ai = getAIInstance();
  
  // We use codeExecution tool to ensure accuracy in calculations and enable plotting.
  chatSession = ai.chats.create({
    model: 'gemini-3-flash-preview',
    config: {
      systemInstruction: `Sen uzman bir Veri Analistisin. Python (Pandas/Matplotlib) kullanarak soruları cevaplarsın.
      
      Sana sağlanan veriyi "df" adında bir pandas DataFrame'e yüklenmiş varsay.
      
      KURALLAR:
      1. Hesaplama, filtreleme, sıralama veya analiz gerektiren her soru için MUTLAKA Python kodu yazıp çalıştır. Kafadan tahmin yapma.
      2. "En yüksek ciro", "Ortalama", "Toplam" gibi sorularda kodu çalıştır ve kesin sonucu söyle.
      3. Grafik istenirse Python (matplotlib/seaborn) kullanarak çiz.
      4. Cevapların kısa, net ve profesyonel olsun. Türkçe konuş.
      
      VERİ:
      ${dataContext}`,
      tools: [{ codeExecution: {} }],
      temperature: 0.1, // Low temperature for precision
    },
  });
};

export interface GeminiResponse {
  text: string;
  images?: string[];
}

export const sendMessageToGemini = async (message: string): Promise<GeminiResponse> => {
  if (!chatSession) {
    throw new Error("Sohbet oturumu başlatılmadı.");
  }

  try {
    const response = await chatSession.sendMessage({ message });
    
    let text = response.text || "Bir cevap oluşturulamadı.";
    const images: string[] = [];

    // Extract images generated by code execution (if any)
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.mimeType.startsWith('image/')) {
          images.push(`data:${part.inlineData.mimeType};base64,${part.inlineData.data}`);
        }
      }
    }

    return { text, images };
  } catch (error) {
    console.error("Gemini Error:", error);
    return { text: "Üzgünüm, bir hata oluştu veya bağlantı zaman aşımına uğradı." };
  }
};